# Generated By: Cursor (Claude Sonnet 4.5)
# GitHub Pull Requests Summary Tool Makefile
# ===========================================

# Include common variables first
include make/common.mk

# Include modular makefiles
include make/env.mk
include make/test.mk
include make/lint.mk
include make/typecheck.mk

.DEFAULT_GOAL := default
.PHONY: help default

help: ## Display this help message
	@echo "GitHub Pull Requests Summary Tool"
	@echo "=================================="
	@echo ""
	@echo "Available targets:"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

default: format lint typecheck test-unit coverage ## Run all validation steps (format, lint, typecheck, test, coverage)
	@printf "$(GREEN)✅ All validation steps passed$(RESET)\n"
