# Generated By: Cursor (Claude Sonnet 4.5)
"""
pytest configuration for integration tests.

This module provides fixtures and configuration for integration tests,
including rate limit checking and GitHub API availability.
"""

import os

import pytest
import requests

from gh_pulls_summary.main import GITHUB_TOKEN


def pytest_configure(config):
    """
    Register custom markers for pytest.
    """
    config.addinivalue_line(
        "markers",
        "integration: mark test as an integration test that requires GitHub API",
    )


@pytest.fixture(scope="session", autouse=True)
def check_rate_limit():
    """
    Check GitHub API rate limit before running integration tests.
    Fail if GITHUB_TOKEN is not set to avoid rate limiting issues.
    """
    # Only check if we're actually running integration tests
    if os.environ.get("RUN_INTEGRATION_TESTS", "").lower() not in ("1", "true", "yes"):
        pytest.skip("Integration tests not enabled. Set RUN_INTEGRATION_TESTS=1")

    # Require GITHUB_TOKEN for integration tests
    if not GITHUB_TOKEN:
        pytest.fail(
            "❌ GITHUB_TOKEN is required for integration tests.\n"
            "Set the GITHUB_TOKEN environment variable with a GitHub personal access token.\n"
            "Without authentication, GitHub's rate limit is only 60 requests/hour, which is insufficient.\n"
            "With authentication, you get 5000 requests/hour.\n\n"
            "To create a token:\n"
            "1. Go to https://github.com/settings/tokens\n"
            "2. Generate a new token (classic) with 'repo' scope\n"
            "3. Set it: export GITHUB_TOKEN=your_token_here"
        )

    # Verify the token works and check rate limit
    try:
        headers = {"Authorization": f"Bearer {GITHUB_TOKEN}"}

        response = requests.get(
            "https://api.github.com/rate_limit", headers=headers, timeout=10
        )

        if response.status_code == 200:
            data = response.json()
            remaining = data.get("rate", {}).get("remaining", 0)
            limit = data.get("rate", {}).get("limit", 5000)

            print(f"\n📊 GitHub API Rate Limit: {remaining}/{limit} remaining")

            # Warn if rate limit is getting low
            if remaining < 100:
                print(
                    f"⚠️  Rate limit is getting low ({remaining} remaining). "
                    f"Tests may fail if rate limit is exhausted."
                )
        else:
            pytest.fail(
                f"❌ GitHub API authentication failed (HTTP {response.status_code}).\n"
                f"Please check your GITHUB_TOKEN is valid."
            )

    except Exception as e:
        pytest.fail(
            f"❌ Could not connect to GitHub API: {e}\n"
            f"Please check your network connection and GITHUB_TOKEN."
        )


@pytest.fixture(scope="session")
def github_rate_limit_info():
    """
    Provide rate limit information to tests that need it.
    """
    try:
        headers = {}
        if GITHUB_TOKEN:
            headers["Authorization"] = f"Bearer {GITHUB_TOKEN}"

        response = requests.get(
            "https://api.github.com/rate_limit", headers=headers, timeout=10
        )

        if response.status_code == 200:
            return response.json().get("rate", {})
    except Exception:
        pass

    return {"limit": 60, "remaining": 0, "reset": 0}
