# Generated By: Cursor (Claude Sonnet 4.5)
# Environment Setup Targets
# ==========================

.PHONY: venv requirements-dev clean-venv

venv: # Create Python virtual environment
	@if [ ! -d "$(VENV_DIR)" ]; then \
		$(PYTHON) -m venv $(VENV_DIR); \
		printf "$(GREEN)✅ Virtual environment created at $(VENV_DIR)$(RESET)\n"; \
	else \
		printf "$(YELLOW)⚠️  Virtual environment already exists at $(VENV_DIR)$(RESET)\n"; \
	fi

requirements-dev: venv # Install all dependencies (runtime + dev)
	@$(VENV_PIP) install --upgrade pip -q
	@$(VENV_PIP) install -r requirements.txt
	@$(VENV_PIP) install -r requirements-test.txt
	@$(VENV_PIP) install -r requirements-dev.txt
	@printf "$(GREEN)✅ All dependencies installed in $(VENV_DIR)$(RESET)\n"

clean-venv: # Remove virtual environment
	@rm -rf $(VENV_DIR) 2>/dev/null || true
	@printf "$(GREEN)✅ Virtual environment removed$(RESET)\n"

