# Generated By: Cursor (Claude Sonnet 4.5)
# Lint Targets
# =============

.PHONY: lint format

lint: requirements-dev # Run linting and type checking
	@$(VENV_PYTHON) -m ruff check . || true
	@$(VENV_PYTHON) -m mypy gh_pulls_summary.py || true
	@printf "$(GREEN)✅ Linting complete$(RESET)\n"

format: requirements-dev # Format code
	@$(VENV_PYTHON) -m ruff format .
	@$(VENV_PYTHON) -m ruff check --fix . || true
	@printf "$(GREEN)✅ Code formatted$(RESET)\n"

