# Generated By: Cursor (Claude Sonnet 4.5)
# Test Targets
# =============

.PHONY: test-all-with-coverage coverage-report coverage-verify

test-all-with-coverage: test-unit test-integration-simple # Run all tests (alias for compatibility)
	@printf "$(GREEN)✅ All tests completed$(RESET)\n"

coverage-report: venv install-requirements-test # Run tests with coverage report (no threshold check)
	@$(VENV_PYTHON) -m coverage run --omit="tests/*,integration_tests/*" -m unittest discover -s tests
	@$(VENV_PYTHON) -m coverage report -m
	@$(VENV_PYTHON) -m coverage xml
	@$(VENV_PYTHON) -m coverage report | tail -1 | awk '{print $$4}' | sed 's/%//' > .coverage-percentage
	@printf "$(GREEN)✅ Coverage report generated$(RESET)\n"

coverage-verify: # Verify coverage meets threshold (run after coverage-report)
	@if [ ! -f .coverage-percentage ]; then \
		printf "$(RED)❌ No coverage data found. Run 'make coverage-report' first.$(RESET)\n"; \
		exit 1; \
	fi; \
	COVERAGE=$$(cat .coverage-percentage); \
	echo "Current coverage: $${COVERAGE}%"; \
	if [ "$$(echo "$${COVERAGE}" | cut -d. -f1)" -lt $(COVERAGE_THRESHOLD) ]; then \
		printf "$(RED)❌ Coverage check failed: $${COVERAGE}%% is below the required $(COVERAGE_THRESHOLD)%% threshold$(RESET)\n"; \
		exit 1; \
	else \
		printf "$(GREEN)✅ Coverage check passed: $${COVERAGE}%% meets the required $(COVERAGE_THRESHOLD)%% threshold$(RESET)\n"; \
	fi

