# Generated By: Cursor (Claude Sonnet 4.5)
"""GitHub Pull Requests Summary Tool."""

__version__ = "1.0.0"
__author__ = "Naveen Malik"
__email__ = "jewzaam@gmail.com"

from .main import main

__all__ = ["main"]
