# Generated By: Claude Code (Claude Opus 4.6)
"""Local git checkout for PR file operations.

Replaces GitHub API calls (fetch_pr_files, fetch_file_content, fetch_pr_diff)
with local git operations using a partial clone. Blobs are fetched lazily —
only when git show/diff actually accesses them.
"""

import logging
import subprocess
import tempfile


class LocalCheckoutError(Exception):
    """Raised when a local checkout operation fails."""


class LocalCheckout:
    """Manages a partial clone for local PR file operations.

    Uses --filter=blob:none --no-checkout to minimize disk and network usage.
    GitHub's refs/pull/<N>/head refs provide access to fork-based PRs without
    adding the fork as a separate remote.
    """

    def __init__(
        self,
        owner: str,
        repo: str,
        github_token: str | None = None,
        base_dir: str | None = None,
    ):
        self.owner = owner
        self.repo = repo
        self.github_token = github_token
        self.base_dir = base_dir or tempfile.mkdtemp(prefix="gh-pulls-summary-")
        self.repo_dir = f"{self.base_dir}/{owner}-{repo}"
        self._fetched_prs: set[int] = set()
        self._fetched_bases: set[str] = set()

    def _clone_url(self) -> str:
        if self.github_token:
            return f"https://x-access-token:{self.github_token}@github.com/{self.owner}/{self.repo}.git"
        return f"https://github.com/{self.owner}/{self.repo}.git"

    def _run_git(
        self, args: list[str], cwd: str | None = None
    ) -> subprocess.CompletedProcess[str]:
        cmd = ["git", *args]
        logging.debug(f"Running: {' '.join(cmd)}")
        result = subprocess.run(
            cmd,
            cwd=cwd or self.repo_dir,
            capture_output=True,
            text=True,
            timeout=300,
            check=False,
        )
        if result.returncode != 0:
            logging.debug(f"git stderr: {result.stderr.strip()}")
        return result

    def ensure_clone(self) -> None:
        logging.info(
            f"Creating partial clone of {self.owner}/{self.repo} at {self.repo_dir}"
        )
        result = subprocess.run(
            [
                "git",
                "clone",
                "--no-checkout",
                "--filter=blob:none",
                "--depth=1",
                self._clone_url(),
                self.repo_dir,
            ],
            capture_output=True,
            text=True,
            timeout=120,
            check=False,
        )
        if result.returncode != 0:
            raise LocalCheckoutError(
                f"Failed to clone {self.owner}/{self.repo}: {result.stderr.strip()}"
            )

    def fetch_pr(self, pr_number: int) -> None:
        if pr_number in self._fetched_prs:
            return
        result = self._run_git(
            [
                "fetch",
                "--depth=1",
                "origin",
                f"pull/{pr_number}/head:refs/pr/{pr_number}",
            ]
        )
        if result.returncode != 0:
            raise LocalCheckoutError(
                f"Failed to fetch PR #{pr_number}: {result.stderr.strip()}"
            )
        self._fetched_prs.add(pr_number)

    def fetch_base(self, base_sha: str) -> None:
        if base_sha in self._fetched_bases:
            return
        # Check if commit already exists locally
        check = self._run_git(["cat-file", "-t", base_sha])
        if check.returncode == 0 and check.stdout.strip() == "commit":
            self._fetched_bases.add(base_sha)
            return
        result = self._run_git(["fetch", "--depth=1", "origin", base_sha])
        if result.returncode != 0:
            raise LocalCheckoutError(
                f"Failed to fetch base {base_sha}: {result.stderr.strip()}"
            )
        self._fetched_bases.add(base_sha)

    def get_changed_files(
        self, base_sha: str, pr_number: int, exclude_deleted: bool = False
    ) -> list[str] | None:
        self.fetch_pr(pr_number)
        self.fetch_base(base_sha)
        cmd = ["diff", "--name-only"]
        if exclude_deleted:
            cmd.append("--diff-filter=ACMR")
        cmd.extend([base_sha, f"refs/pr/{pr_number}"])
        result = self._run_git(cmd)
        if result.returncode != 0:
            logging.warning(
                f"Failed to get changed files for PR #{pr_number}: {result.stderr.strip()}"
            )
            return None
        return [f for f in result.stdout.strip().split("\n") if f]

    def get_file_content(self, pr_number: int, file_path: str) -> str | None:
        self.fetch_pr(pr_number)
        cmd = ["git", "show", f"refs/pr/{pr_number}:{file_path}"]
        try:
            result = subprocess.run(
                cmd,
                cwd=self.repo_dir,
                capture_output=True,
                timeout=300,
                check=False,
            )
        except Exception as e:
            logging.warning(
                f"Failed to get content for {file_path} in PR #{pr_number}: {e}"
            )
            return None
        if result.returncode != 0:
            logging.warning(
                f"Failed to get content for {file_path} in PR #{pr_number}: {result.stderr.decode(errors='replace').strip()}"
            )
            return None
        try:
            return result.stdout.decode()
        except UnicodeDecodeError:
            logging.debug(f"Skipping binary file {file_path} in PR #{pr_number}")
            return None

    def get_diff(self, base_sha: str, pr_number: int) -> str | None:
        self.fetch_pr(pr_number)
        self.fetch_base(base_sha)
        result = self._run_git(["diff", base_sha, f"refs/pr/{pr_number}"])
        if result.returncode != 0:
            logging.warning(
                f"Failed to get diff for PR #{pr_number}: {result.stderr.strip()}"
            )
            return None
        return result.stdout
