# Generated By: Cursor (Claude Sonnet 4.5)
"""
Unit tests for JIRA client functionality.
"""

import unittest
from unittest.mock import Mock, patch

from gh_pulls_summary.jira_client import (
    JiraAuthenticationError,
    JiraClient,
    JiraClientError,
)


class TestJiraClient(unittest.TestCase):
    """Tests for JiraClient class."""

    def test_init_missing_token(self):
        """Test initialization fails without token."""
        with self.assertRaises(ValueError) as context:
            JiraClient(base_url="https://issues.example.com")
        self.assertIn("JIRA token is required", str(context.exception))

    def test_init_with_token(self):
        """Test initialization with token."""
        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
        )
        self.assertEqual(client.token, "testtoken")
        self.assertIn("Authorization", client.session.headers)
        self.assertEqual(client.session.headers["Authorization"], "Bearer testtoken")

    def test_init_with_explicit_rank_field(self):
        """Test initialization with explicit rank field ID."""
        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
            rank_field_id="customfield_12311940",
        )
        self.assertEqual(client._rank_field_id, "customfield_12311940")

    def test_init_missing_url(self):
        """Test initialization fails without base URL."""
        with self.assertRaises(ValueError):
            JiraClient()

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_get_issue_success(self, mock_get):
        """Test successful issue fetch."""
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "key": "TEST-123",
            "fields": {
                "summary": "Test issue",
                "issuetype": {"name": "Feature"},
                "customfield_12311940": "0|i00ywg:9",
            },
        }
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        # Mock the rank field discovery
        client._rank_field_id = "customfield_12311940"

        issue_data = client.get_issue("TEST-123")
        self.assertEqual(issue_data["key"], "TEST-123")
        self.assertEqual(issue_data["fields"]["issuetype"]["name"], "Feature")

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_get_issue_not_found(self, mock_get):
        """Test issue fetch with 404 error."""
        mock_response = Mock()
        mock_response.status_code = 404
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12311940"

        with self.assertRaises(JiraClientError):
            client.get_issue("TEST-999")

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_get_issue_auth_error(self, mock_get):
        """Test issue fetch with authentication error."""
        mock_response = Mock()
        mock_response.status_code = 401
        mock_get.return_value = mock_response

        client = JiraClient(
            base_url="https://issues.example.com",
            token="badtoken",
        )
        client._rank_field_id = "customfield_12311940"

        with self.assertRaises(JiraAuthenticationError):
            client.get_issue("TEST-123")

    def test_extract_rank_value(self):
        """Test extracting rank value from issue data."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {
            "_rank_field_id": "customfield_12311940",
            "fields": {"customfield_12311940": "0|i00ywg:9"},
        }

        rank = client.extract_rank_value(issue_data)
        self.assertEqual(rank, "0|i00ywg:9")

    def test_extract_rank_value_missing(self):
        """Test extracting rank value when not present."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {}}

        rank = client.extract_rank_value(issue_data)
        self.assertIsNone(rank)

    def test_get_issue_type(self):
        """Test extracting issue type from issue data."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {"issuetype": {"name": "Feature"}}}

        issue_type = client.get_issue_type(issue_data)
        self.assertEqual(issue_type, "Feature")

    def test_get_issue_type_missing(self):
        """Test extracting issue type when not present."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {}}

        issue_type = client.get_issue_type(issue_data)
        self.assertIsNone(issue_type)

    def test_get_issue_status(self):
        """Test extracting issue status from issue data."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {"status": {"name": "In Progress"}}}

        issue_status = client.get_issue_status(issue_data)
        self.assertEqual(issue_status, "In Progress")

    def test_get_issue_status_missing(self):
        """Test extracting issue status when not present."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {}}

        issue_status = client.get_issue_status(issue_data)
        self.assertIsNone(issue_status)

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_success(self, mock_make_request):
        """Test successful rank field discovery."""
        # First call: field discovery, second call: get issue
        mock_make_request.side_effect = [
            [
                {
                    "id": "customfield_12345",
                    "name": "Rank",
                    "schema": {"custom": "com.pyxis.greenhopper.jira:gh-lexo-rank"},
                }
            ],
            {"key": "TEST-1", "fields": {"customfield_12345": "0_i00ywg:9"}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery by calling get_issue
        issue = client.get_issue("TEST-1")

        # The rank field should have been discovered
        self.assertEqual(client._rank_field_id, "customfield_12345")
        self.assertIn("_rank_field_id", issue)

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_skip_obsolete(self, mock_make_request):
        """Test that obsolete rank fields are skipped."""
        # First call: field discovery, second call: get issue
        mock_make_request.side_effect = [
            [
                {
                    "id": "customfield_old",
                    "name": "Rank (Obsolete)",
                    "schema": {"custom": "com.pyxis.greenhopper.jira:gh-lexo-rank"},
                },
                {
                    "id": "customfield_12345",
                    "name": "Rank",
                    "schema": {"custom": "com.pyxis.greenhopper.jira:gh-lexo-rank"},
                },
            ],
            {"key": "TEST-1", "fields": {"customfield_12345": "0_i00ywg:9"}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery
        client.get_issue("TEST-1")

        # Should skip the obsolete one and use the non-obsolete
        self.assertEqual(client._rank_field_id, "customfield_12345")

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_not_found(self, mock_make_request):
        """Test when rank field is not found."""
        # First call: field discovery (no rank), second call: get issue
        mock_make_request.side_effect = [
            [
                {
                    "id": "customfield_other",
                    "name": "Some Other Field",
                    "schema": {"custom": "some.other.type"},
                }
            ],
            {"key": "TEST-1", "fields": {}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery
        client.get_issue("TEST-1")

        # Rank field not found
        self.assertIsNone(client._rank_field_id)

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_exception(self, mock_make_request):
        """Test exception during rank field discovery."""
        # First call fails, second call for get_issue succeeds
        mock_make_request.side_effect = [
            Exception("API error"),
            {"key": "TEST-1", "fields": {}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery
        client.get_issue("TEST-1")

        # Should handle exception gracefully
        self.assertIsNone(client._rank_field_id)

    def test_get_issues_metadata_empty(self):
        """Test get_issues_metadata with empty list."""
        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
            rank_field_id="customfield_12345",
        )

        result = client.get_issues_metadata([])

        self.assertEqual(result, {})

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_get_issues_metadata_batch_success(self, mock_make_request):
        """Test get_issues_metadata uses batch API."""
        mock_make_request.return_value = {
            "issues": [
                {
                    "key": "ANSTRAT-1",
                    "fields": {"summary": "Test 1", "customfield_12345": "0|i00001"},
                },
                {
                    "key": "ANSTRAT-3",
                    "fields": {"summary": "Test 3", "customfield_12345": "0|i00003"},
                },
            ]
        }

        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
            rank_field_id="customfield_12345",
        )

        result = client.get_issues_metadata(["ANSTRAT-1", "ANSTRAT-2", "ANSTRAT-3"])

        # Should use batch search API
        mock_make_request.assert_called_once()
        call_args = mock_make_request.call_args
        self.assertIn("search", call_args[0][0])
        self.assertIn("jql", call_args[1]["params"])

        # Should return two successful fetches (ANSTRAT-2 not found)
        self.assertEqual(len(result), 2)
        self.assertIn("ANSTRAT-1", result)
        self.assertIn("ANSTRAT-3", result)
        self.assertNotIn("ANSTRAT-2", result)


class TestJiraIntegrationFunctions(unittest.TestCase):
    """Tests for JIRA integration helper functions in main.py."""

    def test_extract_jira_issue_keys(self):
        """Test extracting JIRA issue keys from URLs."""
        from gh_pulls_summary.main import extract_jira_issue_keys

        url_dict = {
            "ANSTRAT-1660": "https://issues.redhat.com/browse/ANSTRAT-1660",
            "ANSTRAT-1579": "https://issues.redhat.com/browse/ANSTRAT-1579",
        }

        issue_keys = extract_jira_issue_keys(url_dict, r"(ANSTRAT-\d+)")
        self.assertEqual(issue_keys, ["ANSTRAT-1579", "ANSTRAT-1660"])

    def test_extract_jira_issue_keys_empty(self):
        """Test extracting JIRA issue keys from empty dict."""
        from gh_pulls_summary.main import extract_jira_issue_keys

        issue_keys = extract_jira_issue_keys({}, r"(ANSTRAT-\d+)")
        self.assertEqual(issue_keys, [])

    def test_extract_jira_issue_keys_no_match(self):
        """Test extracting JIRA issue keys with no matches."""
        from gh_pulls_summary.main import extract_jira_issue_keys

        url_dict = {"GitHub": "https://github.com/org/repo"}

        issue_keys = extract_jira_issue_keys(url_dict, r"(ANSTRAT-\d+)")
        self.assertEqual(issue_keys, [])

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_single_issue(self, mock_jira_client_class):
        """Test getting rank for PR with single JIRA issue."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Feature"
        mock_client.get_issue_status.return_value = "In Progress"
        mock_client.extract_rank_value.return_value = "0|i00ywg:9"

        # Pre-fetched metadata cache
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "In Progress"},
                    "customfield_12311940": "0|i00ywg:9",
                },
                "_rank_field_id": "customfield_12311940",
            }
        }

        # Issue keys extracted from PR
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Pipe should be replaced with underscore, issue key appended
        self.assertEqual(rank, "0_i00ywg:9 ANSTRAT-1660")

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_multiple_issues(self, mock_jira_client_class):
        """Test getting rank for PR with multiple JIRA issues."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Feature"
        mock_client.get_issue_status.return_value = "Backlog"
        mock_client.extract_rank_value.return_value = "0|i00ywh:"

        # Pre-fetched metadata cache - only contains 1660
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "Backlog"},
                    "customfield_12311940": "0|i00ywh:",
                },
                "_rank_field_id": "customfield_12311940",
            },
        }

        # Issue keys extracted from PR (metadata table specified 1660 as primary)
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Should return rank for the primary issue
        self.assertEqual(rank, "0_i00ywh: ANSTRAT-1660")

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_filter_outcome(self, mock_jira_client_class):
        """Test getting rank filters out Outcome type issues."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Outcome"
        mock_client.get_issue_status.return_value = "In Progress"
        mock_client.extract_rank_value.return_value = "0|i00ywg:9"

        # Pre-fetched metadata cache
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Outcome"},
                    "status": {"name": "In Progress"},
                    "customfield_12311940": "0|i00ywg:9",
                },
                "_rank_field_id": "customfield_12311940",
            }
        }

        # Issue keys extracted from PR
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Should return None because Outcome is filtered out
        self.assertIsNone(rank)

    def test_get_rank_for_pr_no_client(self):
        """Test getting rank with no JIRA client."""
        from gh_pulls_summary.main import get_rank_for_pr

        issue_keys = ["ANSTRAT-1660"]
        jira_metadata_cache = {}

        rank = get_rank_for_pr(None, issue_keys, jira_metadata_cache)
        self.assertIsNone(rank)

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_filter_by_status(self, mock_jira_client_class):
        """Test getting rank filters out issues with non-allowed status."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Feature"
        mock_client.get_issue_status.return_value = "Release Pending"
        mock_client.extract_rank_value.return_value = "0|i00ywg:9"

        # Pre-fetched metadata cache
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "Release Pending"},
                    "customfield_12311940": "0|i00ywg:9",
                },
                "_rank_field_id": "customfield_12311940",
            }
        }

        # Issue keys extracted from PR
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Should return None because Release Pending is not an allowed status
        self.assertIsNone(rank)


class TestFileContentExtraction(unittest.TestCase):
    """Test cases for extracting JIRA issues from file contents."""

    def test_extract_jira_from_file_contents_success(self):
        """Test extracting JIRA issues from file contents."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        file_contents = [
            "Some content with ANSTRAT-1660",
            "Another file mentioning ANSTRAT-1234",
            "And ANSTRAT-1660 again",  # duplicate should be handled
        ]

        issue_keys = extract_jira_from_file_contents(file_contents, [r"(ANSTRAT-\d+)"])
        # Should return sorted unique keys
        self.assertEqual(issue_keys, ["ANSTRAT-1234", "ANSTRAT-1660"])

    def test_extract_jira_from_file_contents_empty(self):
        """Test with empty file contents list."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        issue_keys = extract_jira_from_file_contents([], [r"(ANSTRAT-\d+)"])
        self.assertEqual(issue_keys, [])

    def test_extract_jira_from_file_contents_no_matches(self):
        """Test with files containing no JIRA issues."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        file_contents = ["Just some regular content", "No issues here"]

        issue_keys = extract_jira_from_file_contents(file_contents, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issue_keys, [])

    def test_extract_jira_from_file_contents_multiple_patterns(self):
        """Test extracting JIRA issues with multiple patterns."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        file_contents = [
            "Some content with ANSTRAT-1660",
            "Another file mentioning OTHERJIRA-5678",
            "And ANSTRAT-1234",
        ]

        issue_keys = extract_jira_from_file_contents(
            file_contents, [r"(ANSTRAT-\d+)", r"(OTHERJIRA-\d+)"]
        )
        # Should return sorted unique keys from both patterns
        self.assertEqual(issue_keys, ["ANSTRAT-1234", "ANSTRAT-1660", "OTHERJIRA-5678"])


class TestMetadataExtraction(unittest.TestCase):
    """Test cases for PR metadata table extraction."""

    def test_extract_primary_jira_from_metadata_success(self):
        """Test extracting JIRA from metadata table."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = """
# Some PR Title

| **Feature / Initiative** | [ANSTRAT-1586](https://issues.redhat.com/browse/ANSTRAT-1586) |
| **Description** | Test description |

Some other content with [ANSTRAT-1234](https://issues.redhat.com/browse/ANSTRAT-1234) references.
"""
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, ["ANSTRAT-1586"])

    def test_extract_primary_jira_no_spaces(self):
        """Test extracting JIRA from metadata table without spaces."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "|**Feature/Initiative**|[ANSTRAT-1738](https://issues.redhat.com/browse/ANSTRAT-1738)|"
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, ["ANSTRAT-1738"])

    def test_extract_primary_jira_not_found(self):
        """Test when metadata table is not present."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "Some PR body without metadata table"
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, [])

    def test_extract_primary_jira_empty_body(self):
        """Test with empty PR body."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        issues = extract_primary_jira_from_metadata("", [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, [])

    def test_extract_primary_jira_beyond_50_lines(self):
        """Test that we only look at first 50 lines."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        # Create a body with the metadata table beyond line 50
        pr_body = (
            "\n".join(["line"] * 60)
            + "\n| **Feature / Initiative** | [ANSTRAT-1586](url) |"
        )
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, [])

    def test_extract_primary_jira_multiple_patterns(self):
        """Test extracting JIRA with multiple patterns."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "| **Feature / Initiative** | [OTHERJIRA-5678](url) |"
        issues = extract_primary_jira_from_metadata(
            pr_body, [r"(ANSTRAT-\d+)", r"(OTHERJIRA-\d+)"]
        )
        # Should find the OTHERJIRA issue using the second pattern
        self.assertEqual(issues, ["OTHERJIRA-5678"])

    def test_extract_primary_jira_multiple_issues_in_row(self):
        """Test extracting multiple JIRA issues from same metadata row."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = (
            "| **Feature / Initiative** | [ANSTRAT-1567](url1), [ANSTRAT-1738](url2) |"
        )
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        # Should find both issues
        self.assertEqual(issues, ["ANSTRAT-1567", "ANSTRAT-1738"])

    def test_extract_primary_jira_case_insensitive(self):
        """Test that feature/initiative matching is case-insensitive."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "| **FEATURE / INITIATIVE** | [ANSTRAT-9999](url) |"
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, ["ANSTRAT-9999"])


class TestFileContentFetchingWithJira(unittest.TestCase):
    """Test cases for file content fetching when JIRA integration is enabled."""

    @patch("gh_pulls_summary.main.fetch_file_content")
    @patch("gh_pulls_summary.main.fetch_pr_files")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_fetch_and_process_with_file_contents(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_user_details,
        mock_fetch_reviews,
        mock_fetch_pr_files,
        mock_fetch_file_content,
    ):
        """Test that file contents are fetched when JIRA client is configured."""
        import re

        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock pull requests
        mock_fetch_pull_requests.return_value = [
            {
                "number": 1,
                "title": "Add SDP",
                "user": {"login": "user1"},
                "html_url": "url1",
                "draft": False,
                "created_at": "2025-05-01T12:00:00Z",
                "body": "Some PR body",
                "head": {"sha": "abc123"},
            }
        ]

        # Mock PR files
        mock_fetch_pr_files.return_value = [
            {"filename": "proposals/sdp-001.md"},
            {"filename": "README.md"},
        ]

        # Mock file content
        mock_fetch_file_content.return_value = (
            "# SDP\n| **Feature / Initiative** | [ANSTRAT-1234](url) |"
        )

        # Mock other dependencies
        mock_fetch_issue_events.return_value = []
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {"name": "User", "html_url": "url"}

        # Create mock JIRA client
        jira_client = Mock(spec=JiraClient)
        jira_client.get_issues_metadata.return_value = {
            "ANSTRAT-1234": {
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "In Progress"},
                    "customfield_12345": "0_i00ywg:9",
                }
            }
        }
        jira_client.get_issue_type.return_value = "Feature"
        jira_client.get_issue_status.return_value = "In Progress"
        jira_client.extract_rank_value.return_value = "0_i00ywg:9"
        jira_client._rank_field_id = "customfield_12345"

        # Call with file_include and JIRA client
        file_include = [re.compile(r"proposals/.*\.md$")]
        pull_requests = fetch_and_process_pull_requests(
            "owner",
            "repo",
            file_include=file_include,
            jira_client=jira_client,
            jira_issue_patterns=[r"(ANSTRAT-\d+)"],
            github_token="test_token",
        )

        # Verify file content was fetched
        mock_fetch_file_content.assert_called_once_with(
            "owner", "repo", "proposals/sdp-001.md", "abc123", "test_token"
        )

        # Verify results include rank
        self.assertEqual(len(pull_requests), 1)
        self.assertIn("rank", pull_requests[0])
        self.assertIn("ANSTRAT-1234", pull_requests[0]["rank"])

    @patch("gh_pulls_summary.main.fetch_pr_files")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_fetch_and_process_without_pr_ref(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_user_details,
        mock_fetch_reviews,
        mock_fetch_pr_files,
    ):
        """Test that file content fetching is skipped if no PR ref."""
        import re

        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock pull requests without head SHA
        mock_fetch_pull_requests.return_value = [
            {
                "number": 1,
                "title": "Add feature",
                "user": {"login": "user1"},
                "html_url": "url1",
                "draft": False,
                "created_at": "2025-05-01T12:00:00Z",
                "body": "Some PR body",
                "head": {},  # No SHA
            }
        ]

        # Mock other dependencies
        mock_fetch_issue_events.return_value = []
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {"name": "User", "html_url": "url"}
        # Mock files matching the filter so PR is included
        mock_fetch_pr_files.return_value = [{"filename": "proposals/sdp-001.md"}]

        # Create mock JIRA client
        jira_client = Mock(spec=JiraClient)

        # Call with file_include and JIRA client
        file_include = [re.compile(r"proposals/.*\.md$")]
        pull_requests = fetch_and_process_pull_requests(
            "owner",
            "repo",
            file_include=file_include,
            jira_client=jira_client,
            jira_issue_patterns=[r"(ANSTRAT-\d+)"],
            github_token="test_token",
        )

        # Verify PR was included (file matched filter)
        # But file content fetch was skipped (no PR ref)
        self.assertEqual(len(pull_requests), 1)
        # Should still return PR without rank since no ref to fetch files


if __name__ == "__main__":
    unittest.main()
