# Generated By: Claude Code (Claude Opus 4.6)
import logging
import unittest
from unittest.mock import MagicMock, patch

from gh_pulls_summary.local_checkout import LocalCheckout, LocalCheckoutError

logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s - %(levelname)s - %(message)s"
)


class TestLocalCheckoutInit(unittest.TestCase):
    @patch(
        "gh_pulls_summary.local_checkout.tempfile.mkdtemp",
        return_value="/tmp/gh-pulls-summary-abc123",
    )
    def test_defaults(self, mock_mkdtemp):
        lc = LocalCheckout("myorg", "myrepo")
        self.assertEqual(lc.owner, "myorg")
        self.assertEqual(lc.repo, "myrepo")
        self.assertIsNone(lc.github_token)
        self.assertEqual(lc.base_dir, "/tmp/gh-pulls-summary-abc123")
        self.assertEqual(lc.repo_dir, "/tmp/gh-pulls-summary-abc123/myorg-myrepo")
        mock_mkdtemp.assert_called_once_with(prefix="gh-pulls-summary-")

    def test_custom_base_dir(self):
        lc = LocalCheckout("org", "repo", base_dir="/tmp/custom")
        self.assertEqual(lc.base_dir, "/tmp/custom")
        self.assertEqual(lc.repo_dir, "/tmp/custom/org-repo")

    def test_clone_url_without_token(self):
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        self.assertEqual(lc._clone_url(), "https://github.com/org/repo.git")

    def test_clone_url_with_token(self):
        lc = LocalCheckout(
            "org", "repo", github_token="ghp_abc123", base_dir="/tmp/test"
        )
        self.assertEqual(
            lc._clone_url(),
            "https://x-access-token:ghp_abc123@github.com/org/repo.git",
        )


class TestEnsureClone(unittest.TestCase):
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_fresh_clone(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        lc.ensure_clone()

        cmd = mock_run.call_args[0][0]
        self.assertIn("clone", cmd)
        self.assertIn("--no-checkout", cmd)
        self.assertIn("--filter=blob:none", cmd)
        self.assertIn("--depth=1", cmd)

    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_clone_failure_raises(self, mock_run):
        mock_run.return_value = MagicMock(
            returncode=128, stdout="", stderr="fatal: repository not found"
        )
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        with self.assertRaises(LocalCheckoutError) as ctx:
            lc.ensure_clone()
        self.assertIn("repository not found", str(ctx.exception))


class TestFetchPr(unittest.TestCase):
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_fetch_pr_success(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        lc.fetch_pr(42)

        cmd = mock_run.call_args[0][0]
        self.assertIn("fetch", cmd)
        self.assertIn("pull/42/head:refs/pr/42", cmd)

    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_fetch_pr_cached(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        lc.fetch_pr(42)
        lc.fetch_pr(42)

        self.assertEqual(mock_run.call_count, 1)

    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_fetch_pr_failure(self, mock_run):
        mock_run.return_value = MagicMock(
            returncode=128, stdout="", stderr="fatal: couldn't find remote ref"
        )
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        with self.assertRaises(LocalCheckoutError):
            lc.fetch_pr(999)


class TestFetchBase(unittest.TestCase):
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_fetch_base_already_present(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="commit\n", stderr="")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        lc.fetch_base("abc123")

        cmd = mock_run.call_args[0][0]
        self.assertIn("cat-file", cmd)
        self.assertEqual(mock_run.call_count, 1)

    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_fetch_base_needs_fetch(self, mock_run):
        mock_run.side_effect = [
            MagicMock(returncode=1, stdout="", stderr=""),
            MagicMock(returncode=0, stdout="", stderr=""),
        ]
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        lc.fetch_base("abc123")

        self.assertEqual(mock_run.call_count, 2)
        fetch_cmd = mock_run.call_args_list[1][0][0]
        self.assertIn("fetch", fetch_cmd)
        self.assertIn("abc123", fetch_cmd)

    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_fetch_base_cached(self, mock_run):
        mock_run.return_value = MagicMock(returncode=0, stdout="commit\n", stderr="")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        lc.fetch_base("abc123")
        lc.fetch_base("abc123")

        self.assertEqual(mock_run.call_count, 1)


class TestGetChangedFiles(unittest.TestCase):
    @patch.object(LocalCheckout, "fetch_base")
    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_returns_file_list(self, mock_run, mock_fetch_pr, mock_fetch_base):
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout="src/main.py\nsrc/utils.py\nREADME.md\n",
            stderr="",
        )
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_changed_files("base_sha", 42)

        self.assertEqual(result, ["src/main.py", "src/utils.py", "README.md"])
        mock_fetch_pr.assert_called_once_with(42)
        mock_fetch_base.assert_called_once_with("base_sha")

    @patch.object(LocalCheckout, "fetch_base")
    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_returns_none_on_failure(self, mock_run, mock_fetch_pr, mock_fetch_base):
        mock_run.return_value = MagicMock(returncode=1, stdout="", stderr="error")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_changed_files("base_sha", 42)

        self.assertIsNone(result)

    @patch.object(LocalCheckout, "fetch_base")
    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_empty_diff_returns_empty_list(
        self, mock_run, mock_fetch_pr, mock_fetch_base
    ):
        mock_run.return_value = MagicMock(returncode=0, stdout="", stderr="")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_changed_files("base_sha", 42)

        self.assertEqual(result, [])


class TestGetFileContent(unittest.TestCase):
    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_returns_content(self, mock_run, mock_fetch_pr):
        mock_run.return_value = MagicMock(
            returncode=0, stdout=b"file content here", stderr=b""
        )
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_file_content(42, "src/main.py")

        self.assertEqual(result, "file content here")
        cmd = mock_run.call_args[0][0]
        self.assertIn("show", cmd)
        self.assertIn("refs/pr/42:src/main.py", cmd)

    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_returns_none_on_failure(self, mock_run, mock_fetch_pr):
        mock_run.return_value = MagicMock(
            returncode=128, stdout=b"", stderr=b"fatal: path not found"
        )
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_file_content(42, "nonexistent.py")

        self.assertIsNone(result)

    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_returns_none_for_binary(self, mock_run, mock_fetch_pr):
        mock_run.return_value = MagicMock(
            returncode=0, stdout=b"\x89PNG\r\n\x1a\n", stderr=b""
        )
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_file_content(42, "image.png")

        self.assertIsNone(result)


class TestGetDiff(unittest.TestCase):
    @patch.object(LocalCheckout, "fetch_base")
    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_returns_diff(self, mock_run, mock_fetch_pr, mock_fetch_base):
        diff_text = "--- a/file.py\n+++ b/file.py\n@@ -1 +1 @@\n-old\n+new\n"
        mock_run.return_value = MagicMock(returncode=0, stdout=diff_text, stderr="")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_diff("base_sha", 42)

        self.assertEqual(result, diff_text)
        mock_fetch_pr.assert_called_once_with(42)
        mock_fetch_base.assert_called_once_with("base_sha")

    @patch.object(LocalCheckout, "fetch_base")
    @patch.object(LocalCheckout, "fetch_pr")
    @patch("gh_pulls_summary.local_checkout.subprocess.run")
    def test_returns_none_on_failure(self, mock_run, mock_fetch_pr, mock_fetch_base):
        mock_run.return_value = MagicMock(returncode=1, stdout="", stderr="error")
        lc = LocalCheckout("org", "repo", base_dir="/tmp/test")
        result = lc.get_diff("base_sha", 42)

        self.assertIsNone(result)


if __name__ == "__main__":
    unittest.main()
