# Generated By: Cursor (Claude Sonnet 4.5)
"""
Unit tests for JIRA client functionality.
"""

import unittest
from unittest.mock import Mock, patch

from gh_pulls_summary.jira_client import (
    JiraAuthenticationError,
    JiraClient,
    JiraClientError,
)


class TestJiraClient(unittest.TestCase):
    """Tests for JiraClient class."""

    def test_init_missing_token(self):
        """Test initialization fails without token."""
        with self.assertRaises(ValueError) as context:
            JiraClient(base_url="https://issues.example.com")
        self.assertIn("JIRA token is required", str(context.exception))

    def test_init_with_token(self):
        """Test initialization with token."""
        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
        )
        self.assertEqual(client.token, "testtoken")
        self.assertIn("Authorization", client.session.headers)
        self.assertEqual(client.session.headers["Authorization"], "Bearer testtoken")

    def test_init_with_explicit_rank_field(self):
        """Test initialization with explicit rank field ID."""
        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
            rank_field_id="customfield_12311940",
        )
        self.assertEqual(client._rank_field_id, "customfield_12311940")

    def test_init_missing_url(self):
        """Test initialization fails without base URL."""
        with self.assertRaises(ValueError):
            JiraClient()

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_get_issue_success(self, mock_get):
        """Test successful issue fetch."""
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "key": "TEST-123",
            "fields": {
                "summary": "Test issue",
                "issuetype": {"name": "Feature"},
                "customfield_12311940": "0|i00ywg:9",
            },
        }
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        # Mock the rank field discovery
        client._rank_field_id = "customfield_12311940"

        issue_data = client.get_issue("TEST-123")
        self.assertEqual(issue_data["key"], "TEST-123")
        self.assertEqual(issue_data["fields"]["issuetype"]["name"], "Feature")

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_get_issue_not_found(self, mock_get):
        """Test issue fetch with 404 error."""
        mock_response = Mock()
        mock_response.status_code = 404
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12311940"

        with self.assertRaises(JiraClientError):
            client.get_issue("TEST-999")

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_get_issue_auth_error(self, mock_get):
        """Test issue fetch with authentication error."""
        mock_response = Mock()
        mock_response.status_code = 401
        mock_get.return_value = mock_response

        client = JiraClient(
            base_url="https://issues.example.com",
            token="badtoken",
        )
        client._rank_field_id = "customfield_12311940"

        with self.assertRaises(JiraAuthenticationError):
            client.get_issue("TEST-123")

    def test_extract_rank_value(self):
        """Test extracting rank value from issue data."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {
            "_rank_field_id": "customfield_12311940",
            "fields": {"customfield_12311940": "0|i00ywg:9"},
        }

        rank = client.extract_rank_value(issue_data)
        self.assertEqual(rank, "0|i00ywg:9")

    def test_extract_rank_value_missing(self):
        """Test extracting rank value when not present."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {}}

        rank = client.extract_rank_value(issue_data)
        self.assertIsNone(rank)

    def test_get_issue_type(self):
        """Test extracting issue type from issue data."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {"issuetype": {"name": "Feature"}}}

        issue_type = client.get_issue_type(issue_data)
        self.assertEqual(issue_type, "Feature")

    def test_get_issue_type_missing(self):
        """Test extracting issue type when not present."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {}}

        issue_type = client.get_issue_type(issue_data)
        self.assertIsNone(issue_type)

    def test_get_issue_status(self):
        """Test extracting issue status from issue data."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {"status": {"name": "In Progress"}}}

        issue_status = client.get_issue_status(issue_data)
        self.assertEqual(issue_status, "In Progress")

    def test_get_issue_status_missing(self):
        """Test extracting issue status when not present."""
        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {"fields": {}}

        issue_status = client.get_issue_status(issue_data)
        self.assertIsNone(issue_status)

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_success(self, mock_make_request):
        """Test successful rank field discovery."""
        # First call: field discovery, second call: get issue
        mock_make_request.side_effect = [
            [
                {
                    "id": "customfield_12345",
                    "name": "Rank",
                    "schema": {"custom": "com.pyxis.greenhopper.jira:gh-lexo-rank"},
                }
            ],
            {"key": "TEST-1", "fields": {"customfield_12345": "0_i00ywg:9"}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery by calling get_issue
        issue = client.get_issue("TEST-1")

        # The rank field should have been discovered
        self.assertEqual(client._rank_field_id, "customfield_12345")
        self.assertIn("_rank_field_id", issue)

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_skip_obsolete(self, mock_make_request):
        """Test that obsolete rank fields are skipped."""
        # First call: field discovery, second call: get issue
        mock_make_request.side_effect = [
            [
                {
                    "id": "customfield_old",
                    "name": "Rank (Obsolete)",
                    "schema": {"custom": "com.pyxis.greenhopper.jira:gh-lexo-rank"},
                },
                {
                    "id": "customfield_12345",
                    "name": "Rank",
                    "schema": {"custom": "com.pyxis.greenhopper.jira:gh-lexo-rank"},
                },
            ],
            {"key": "TEST-1", "fields": {"customfield_12345": "0_i00ywg:9"}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery
        client.get_issue("TEST-1")

        # Should skip the obsolete one and use the non-obsolete
        self.assertEqual(client._rank_field_id, "customfield_12345")

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_not_found(self, mock_make_request):
        """Test when rank field is not found."""
        # First call: field discovery (no rank), second call: get issue
        mock_make_request.side_effect = [
            [
                {
                    "id": "customfield_other",
                    "name": "Some Other Field",
                    "schema": {"custom": "some.other.type"},
                }
            ],
            {"key": "TEST-1", "fields": {}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery
        client.get_issue("TEST-1")

        # Rank field not found
        self.assertIsNone(client._rank_field_id)

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_discover_rank_field_exception(self, mock_make_request):
        """Test exception during rank field discovery."""
        # First call fails, second call for get_issue succeeds
        mock_make_request.side_effect = [
            Exception("API error"),
            {"key": "TEST-1", "fields": {}},
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        # Trigger lazy discovery
        client.get_issue("TEST-1")

        # Should handle exception gracefully
        self.assertIsNone(client._rank_field_id)

    def test_get_issues_metadata_empty(self):
        """Test get_issues_metadata with empty list."""
        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
            rank_field_id="customfield_12345",
        )

        result = client.get_issues_metadata([])

        self.assertEqual(result, {})

    @patch("gh_pulls_summary.jira_client.JiraClient._make_request")
    def test_get_issues_metadata_batch_success(self, mock_make_request):
        """Test get_issues_metadata uses batch API."""
        mock_make_request.return_value = {
            "issues": [
                {
                    "key": "ANSTRAT-1",
                    "fields": {"summary": "Test 1", "customfield_12345": "0|i00001"},
                },
                {
                    "key": "ANSTRAT-3",
                    "fields": {"summary": "Test 3", "customfield_12345": "0|i00003"},
                },
            ]
        }

        client = JiraClient(
            base_url="https://issues.example.com",
            token="testtoken",
            rank_field_id="customfield_12345",
        )

        result = client.get_issues_metadata(["ANSTRAT-1", "ANSTRAT-2", "ANSTRAT-3"])

        # Should use batch search API
        mock_make_request.assert_called_once()
        call_args = mock_make_request.call_args
        self.assertIn("search", call_args[0][0])
        self.assertIn("jql", call_args[1]["params"])

        # Should return two successful fetches (ANSTRAT-2 not found)
        self.assertEqual(len(result), 2)
        self.assertIn("ANSTRAT-1", result)
        self.assertIn("ANSTRAT-3", result)
        self.assertNotIn("ANSTRAT-2", result)


class TestJiraIntegrationFunctions(unittest.TestCase):
    """Tests for JIRA integration helper functions in main.py."""

    def test_extract_jira_issue_keys(self):
        """Test extracting JIRA issue keys from URLs."""
        from gh_pulls_summary.main import extract_jira_issue_keys

        url_dict = {
            "ANSTRAT-1660": "https://issues.redhat.com/browse/ANSTRAT-1660",
            "ANSTRAT-1579": "https://issues.redhat.com/browse/ANSTRAT-1579",
        }

        issue_keys = extract_jira_issue_keys(url_dict, r"(ANSTRAT-\d+)")
        self.assertEqual(issue_keys, ["ANSTRAT-1579", "ANSTRAT-1660"])

    def test_extract_jira_issue_keys_empty(self):
        """Test extracting JIRA issue keys from empty dict."""
        from gh_pulls_summary.main import extract_jira_issue_keys

        issue_keys = extract_jira_issue_keys({}, r"(ANSTRAT-\d+)")
        self.assertEqual(issue_keys, [])

    def test_extract_jira_issue_keys_no_match(self):
        """Test extracting JIRA issue keys with no matches."""
        from gh_pulls_summary.main import extract_jira_issue_keys

        url_dict = {"GitHub": "https://github.com/org/repo"}

        issue_keys = extract_jira_issue_keys(url_dict, r"(ANSTRAT-\d+)")
        self.assertEqual(issue_keys, [])

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_single_issue(self, mock_jira_client_class):
        """Test getting rank for PR with single JIRA issue."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Feature"
        mock_client.get_issue_status.return_value = "In Progress"
        mock_client.extract_rank_value.return_value = "0|i00ywg:9"

        # Pre-fetched metadata cache
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "In Progress"},
                    "customfield_12311940": "0|i00ywg:9",
                },
                "_rank_field_id": "customfield_12311940",
            }
        }

        # Issue keys extracted from PR
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Pipe should be replaced with underscore, issue key appended
        self.assertEqual(rank, "0_i00ywg:9 ANSTRAT-1660")

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_multiple_issues(self, mock_jira_client_class):
        """Test getting rank for PR with multiple JIRA issues."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Feature"
        mock_client.get_issue_status.return_value = "Backlog"
        mock_client.extract_rank_value.return_value = "0|i00ywh:"

        # Pre-fetched metadata cache - only contains 1660
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "Backlog"},
                    "customfield_12311940": "0|i00ywh:",
                },
                "_rank_field_id": "customfield_12311940",
            },
        }

        # Issue keys extracted from PR (metadata table specified 1660 as primary)
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Should return rank for the primary issue
        self.assertEqual(rank, "0_i00ywh: ANSTRAT-1660")

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_filter_outcome(self, mock_jira_client_class):
        """Test getting rank filters out Outcome type issues."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Outcome"
        mock_client.get_issue_status.return_value = "In Progress"
        mock_client.extract_rank_value.return_value = "0|i00ywg:9"

        # Pre-fetched metadata cache
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Outcome"},
                    "status": {"name": "In Progress"},
                    "customfield_12311940": "0|i00ywg:9",
                },
                "_rank_field_id": "customfield_12311940",
            }
        }

        # Issue keys extracted from PR
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Should return None because Outcome is filtered out
        self.assertIsNone(rank)

    def test_get_rank_for_pr_no_client(self):
        """Test getting rank with no JIRA client."""
        from gh_pulls_summary.main import get_rank_for_pr

        issue_keys = ["ANSTRAT-1660"]
        jira_metadata_cache = {}

        rank = get_rank_for_pr(None, issue_keys, jira_metadata_cache)
        self.assertIsNone(rank)

    @patch("gh_pulls_summary.main.JiraClient")
    def test_get_rank_for_pr_filter_by_status(self, mock_jira_client_class):
        """Test getting rank filters out issues with non-allowed status."""
        from gh_pulls_summary.main import get_rank_for_pr

        # Mock JIRA client
        mock_client = Mock()
        mock_client.get_issue_type.return_value = "Feature"
        mock_client.get_issue_status.return_value = "Release Pending"
        mock_client.extract_rank_value.return_value = "0|i00ywg:9"

        # Pre-fetched metadata cache
        jira_metadata_cache = {
            "ANSTRAT-1660": {
                "key": "ANSTRAT-1660",
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "Release Pending"},
                    "customfield_12311940": "0|i00ywg:9",
                },
                "_rank_field_id": "customfield_12311940",
            }
        }

        # Issue keys extracted from PR
        issue_keys = ["ANSTRAT-1660"]

        rank = get_rank_for_pr(mock_client, issue_keys, jira_metadata_cache)
        # Should return None because Release Pending is not an allowed status
        self.assertIsNone(rank)


class TestFileContentExtraction(unittest.TestCase):
    """Test cases for extracting JIRA issues from file contents."""

    def test_extract_jira_from_file_contents_success(self):
        """Test extracting JIRA issues from file contents."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        file_contents = [
            "Some content with ANSTRAT-1660",
            "Another file mentioning ANSTRAT-1234",
            "And ANSTRAT-1660 again",  # duplicate should be handled
        ]

        issue_keys = extract_jira_from_file_contents(file_contents, [r"(ANSTRAT-\d+)"])
        # Should return sorted unique keys
        self.assertEqual(issue_keys, ["ANSTRAT-1234", "ANSTRAT-1660"])

    def test_extract_jira_from_file_contents_empty(self):
        """Test with empty file contents list."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        issue_keys = extract_jira_from_file_contents([], [r"(ANSTRAT-\d+)"])
        self.assertEqual(issue_keys, [])

    def test_extract_jira_from_file_contents_no_matches(self):
        """Test with files containing no JIRA issues."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        file_contents = ["Just some regular content", "No issues here"]

        issue_keys = extract_jira_from_file_contents(file_contents, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issue_keys, [])

    def test_extract_jira_from_file_contents_multiple_patterns(self):
        """Test extracting JIRA issues with multiple patterns."""
        from gh_pulls_summary.main import extract_jira_from_file_contents

        file_contents = [
            "Some content with ANSTRAT-1660",
            "Another file mentioning OTHERJIRA-5678",
            "And ANSTRAT-1234",
        ]

        issue_keys = extract_jira_from_file_contents(
            file_contents, [r"(ANSTRAT-\d+)", r"(OTHERJIRA-\d+)"]
        )
        # Should return sorted unique keys from both patterns
        self.assertEqual(issue_keys, ["ANSTRAT-1234", "ANSTRAT-1660", "OTHERJIRA-5678"])


class TestMetadataExtraction(unittest.TestCase):
    """Test cases for PR metadata table extraction."""

    def test_extract_primary_jira_from_metadata_success(self):
        """Test extracting JIRA from metadata table."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = """
# Some PR Title

| **Feature / Initiative** | [ANSTRAT-1586](https://issues.redhat.com/browse/ANSTRAT-1586) |
| **Description** | Test description |

Some other content with [ANSTRAT-1234](https://issues.redhat.com/browse/ANSTRAT-1234) references.
"""
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, ["ANSTRAT-1586"])

    def test_extract_primary_jira_no_spaces(self):
        """Test extracting JIRA from metadata table without spaces."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "|**Feature/Initiative**|[ANSTRAT-1738](https://issues.redhat.com/browse/ANSTRAT-1738)|"
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, ["ANSTRAT-1738"])

    def test_extract_primary_jira_not_found(self):
        """Test when metadata table is not present."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "Some PR body without metadata table"
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, [])

    def test_extract_primary_jira_empty_body(self):
        """Test with empty PR body."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        issues = extract_primary_jira_from_metadata("", [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, [])

    def test_extract_primary_jira_beyond_50_lines(self):
        """Test that we only look at first 50 lines."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        # Create a body with the metadata table beyond line 50
        pr_body = (
            "\n".join(["line"] * 60)
            + "\n| **Feature / Initiative** | [ANSTRAT-1586](url) |"
        )
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, [])

    def test_extract_primary_jira_multiple_patterns(self):
        """Test extracting JIRA with multiple patterns."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "| **Feature / Initiative** | [OTHERJIRA-5678](url) |"
        issues = extract_primary_jira_from_metadata(
            pr_body, [r"(ANSTRAT-\d+)", r"(OTHERJIRA-\d+)"]
        )
        # Should find the OTHERJIRA issue using the second pattern
        self.assertEqual(issues, ["OTHERJIRA-5678"])

    def test_extract_primary_jira_multiple_issues_in_row(self):
        """Test extracting multiple JIRA issues from same metadata row."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = (
            "| **Feature / Initiative** | [ANSTRAT-1567](url1), [ANSTRAT-1738](url2) |"
        )
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        # Should find both issues
        self.assertEqual(issues, ["ANSTRAT-1567", "ANSTRAT-1738"])

    def test_extract_primary_jira_case_insensitive(self):
        """Test that feature/initiative matching is case-insensitive."""
        from gh_pulls_summary.main import extract_primary_jira_from_metadata

        pr_body = "| **FEATURE / INITIATIVE** | [ANSTRAT-9999](url) |"
        issues = extract_primary_jira_from_metadata(pr_body, [r"(ANSTRAT-\d+)"])
        self.assertEqual(issues, ["ANSTRAT-9999"])


class TestFileContentFetchingWithJira(unittest.TestCase):
    """Test cases for file content fetching when JIRA integration is enabled."""

    @patch("gh_pulls_summary.main.fetch_file_content")
    @patch("gh_pulls_summary.main.fetch_pr_files")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_fetch_and_process_with_file_contents(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_user_details,
        mock_fetch_reviews,
        mock_fetch_pr_files,
        mock_fetch_file_content,
    ):
        """Test that file contents are fetched when JIRA client is configured."""
        import re

        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock pull requests
        mock_fetch_pull_requests.return_value = [
            {
                "number": 1,
                "title": "Add SDP",
                "user": {"login": "user1"},
                "html_url": "url1",
                "draft": False,
                "created_at": "2025-05-01T12:00:00Z",
                "body": "Some PR body",
                "head": {"sha": "abc123"},
            }
        ]

        # Mock PR files
        mock_fetch_pr_files.return_value = [
            {"filename": "proposals/sdp-001.md"},
            {"filename": "README.md"},
        ]

        # Mock file content
        mock_fetch_file_content.return_value = (
            "# SDP\n| **Feature / Initiative** | [ANSTRAT-1234](url) |"
        )

        # Mock other dependencies
        mock_fetch_issue_events.return_value = []
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {"name": "User", "html_url": "url"}

        # Create mock JIRA client
        jira_client = Mock(spec=JiraClient)
        jira_client.base_url = "https://issues.example.com"
        jira_client.get_issues_metadata.return_value = {
            "ANSTRAT-1234": {
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "In Progress"},
                    "customfield_12345": "0_i00ywg:9",
                    "summary": "Test feature from file content",
                }
            }
        }
        jira_client.get_issue_type.return_value = "Feature"
        jira_client.get_issue_status.return_value = "In Progress"
        jira_client.extract_rank_value.return_value = "0_i00ywg:9"
        jira_client._rank_field_id = "customfield_12345"

        # Call with file_include and JIRA client
        file_include = [re.compile(r"proposals/.*\.md$")]
        pull_requests, _ = fetch_and_process_pull_requests(
            "owner",
            "repo",
            file_include=file_include,
            jira_client=jira_client,
            jira_issue_patterns=[r"(ANSTRAT-\d+)"],
            github_token="test_token",
        )

        # Verify file content was fetched
        mock_fetch_file_content.assert_called_once_with(
            "owner", "repo", "proposals/sdp-001.md", "abc123", "test_token"
        )

        # Verify results include rank
        self.assertEqual(len(pull_requests), 1)
        self.assertIn("rank", pull_requests[0])
        self.assertIn("ANSTRAT-1234", pull_requests[0]["rank"])

    @patch("gh_pulls_summary.main.fetch_pr_files")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_fetch_and_process_without_pr_ref(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_user_details,
        mock_fetch_reviews,
        mock_fetch_pr_files,
    ):
        """Test that file content fetching is skipped if no PR ref."""
        import re

        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock pull requests without head SHA
        mock_fetch_pull_requests.return_value = [
            {
                "number": 1,
                "title": "Add feature",
                "user": {"login": "user1"},
                "html_url": "url1",
                "draft": False,
                "created_at": "2025-05-01T12:00:00Z",
                "body": "Some PR body",
                "head": {},  # No SHA
            }
        ]

        # Mock other dependencies
        mock_fetch_issue_events.return_value = []
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {"name": "User", "html_url": "url"}
        # Mock files matching the filter so PR is included
        mock_fetch_pr_files.return_value = [{"filename": "proposals/sdp-001.md"}]

        # Create mock JIRA client
        jira_client = Mock(spec=JiraClient)

        # Call with file_include and JIRA client
        file_include = [re.compile(r"proposals/.*\.md$")]
        pull_requests, _ = fetch_and_process_pull_requests(
            "owner",
            "repo",
            file_include=file_include,
            jira_client=jira_client,
            jira_issue_patterns=[r"(ANSTRAT-\d+)"],
            github_token="test_token",
        )

        # Verify PR was included (file matched filter)
        # But file content fetch was skipped (no PR ref)
        self.assertEqual(len(pull_requests), 1)
        # Should still return PR without rank since no ref to fetch files


class TestJiraInclude(unittest.TestCase):
    """Test cases for jira-include feature."""

    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_jira_include_with_no_prs(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_user_details,
        mock_fetch_reviews,
    ):
        """Test that jira-include creates synthetic entries when no PRs exist."""
        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock no pull requests
        mock_fetch_pull_requests.return_value = []

        # Mock other dependencies
        mock_fetch_issue_events.return_value = []
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {"name": "User", "html_url": "url"}

        # Create mock JIRA client
        jira_client = Mock(spec=JiraClient)
        jira_client.base_url = "https://issues.example.com"
        jira_client.get_issues_metadata.return_value = {
            "ANSTRAT-1234": {
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "Backlog"},
                    "customfield_12345": "0|i00001",
                    "summary": "Test included JIRA issue",
                },
                "_rank_field_id": "customfield_12345",
            }
        }
        jira_client.get_issue_type.return_value = "Feature"
        jira_client.get_issue_status.return_value = "Backlog"
        jira_client.extract_rank_value.return_value = "0|i00001"

        # Call with jira-include
        pull_requests, jira_issues = fetch_and_process_pull_requests(
            "owner",
            "repo",
            jira_client=jira_client,
            jira_issue_patterns=[r"(ANSTRAT-\d+)"],
            jira_include=["ANSTRAT-1234"],
            github_token="test_token",
        )

        # Verify no synthetic entry in pull_requests (yet - that happens in generate_markdown_output)
        self.assertEqual(len(pull_requests), 0)

        # Verify JIRA issues dict was populated with the jira-include issue
        self.assertEqual(len(jira_issues), 1)
        self.assertIn("ANSTRAT-1234", jira_issues)
        # Verify JIRA data is populated correctly
        jira_data = jira_issues["ANSTRAT-1234"]
        self.assertIsNotNone(jira_data["title"])
        self.assertIn("browse/ANSTRAT-1234", jira_data["url"])
        self.assertIn("ANSTRAT-1234", jira_data["rank"])

    @patch("gh_pulls_summary.main.fetch_pr_files")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_jira_include_no_duplicate_if_pr_exists(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_user_details,
        mock_fetch_reviews,
        mock_fetch_pr_files,
    ):
        """Test that jira-include doesn't duplicate if PR already has the issue."""

        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock pull requests with JIRA issue in body
        mock_fetch_pull_requests.return_value = [
            {
                "number": 1,
                "title": "Add feature",
                "user": {"login": "user1"},
                "html_url": "url1",
                "draft": False,
                "created_at": "2025-05-01T12:00:00Z",
                "body": "| **Feature / Initiative** | [ANSTRAT-1234](url) |",
                "head": {},
            }
        ]

        # Mock other dependencies
        mock_fetch_issue_events.return_value = []
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {"name": "User", "html_url": "url"}
        mock_fetch_pr_files.return_value = []

        # Create mock JIRA client
        jira_client = Mock(spec=JiraClient)
        jira_client.base_url = "https://issues.example.com"
        jira_client.get_issues_metadata.return_value = {
            "ANSTRAT-1234": {
                "fields": {
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "In Progress"},
                    "customfield_12345": "0|i00001",
                },
                "_rank_field_id": "customfield_12345",
            }
        }
        jira_client.get_issue_type.return_value = "Feature"
        jira_client.get_issue_status.return_value = "In Progress"
        jira_client.extract_rank_value.return_value = "0|i00001"

        # Call with jira-include
        pull_requests, _ = fetch_and_process_pull_requests(
            "owner",
            "repo",
            jira_client=jira_client,
            jira_issue_patterns=[r"(ANSTRAT-\d+)"],
            jira_include=["ANSTRAT-1234"],
            github_token="test_token",
        )

        # Verify only one entry (the PR, not a duplicate synthetic entry)
        self.assertEqual(len(pull_requests), 1)
        self.assertEqual(pull_requests[0]["number"], 1)
        self.assertIn("ANSTRAT-1234", pull_requests[0]["rank"])

    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_jira_include_skips_invalid_issue(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_user_details,
        mock_fetch_reviews,
    ):
        """Test that jira-include skips issues that have no rank."""
        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock no pull requests
        mock_fetch_pull_requests.return_value = []

        # Mock other dependencies
        mock_fetch_issue_events.return_value = []
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {"name": "User", "html_url": "url"}

        # Create mock JIRA client - issue is Outcome type (filtered out)
        jira_client = Mock(spec=JiraClient)
        jira_client.base_url = "https://issues.example.com"
        jira_client.get_issues_metadata.return_value = {
            "ANSTRAT-9999": {
                "fields": {
                    "issuetype": {"name": "Outcome"},  # Not Feature or Initiative
                    "status": {"name": "Backlog"},
                    "customfield_12345": "0|i00001",
                },
                "_rank_field_id": "customfield_12345",
            }
        }
        jira_client.get_issue_type.return_value = "Outcome"
        jira_client.get_issue_status.return_value = "Backlog"
        jira_client.extract_rank_value.return_value = "0|i00001"

        # Call with jira-include
        pull_requests, _ = fetch_and_process_pull_requests(
            "owner",
            "repo",
            jira_client=jira_client,
            jira_issue_patterns=[r"(ANSTRAT-\d+)"],
            jira_include=["ANSTRAT-9999"],
            github_token="test_token",
        )

        # Verify no synthetic entry was created (Outcome type is filtered)
        self.assertEqual(len(pull_requests), 0)


class TestJiraHierarchyTraversal(unittest.TestCase):
    """Test cases for JIRA hierarchy traversal to find Feature/Initiative ancestors."""

    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_rank_from_ancestor_when_pr_references_non_feature(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_reviews,
        mock_fetch_user_details,
    ):
        """
        Test that when a PR references a non-Feature/Initiative issue (e.g., SDP, Proposal, AAP),
        the code traverses up the JIRA hierarchy to find the Feature or Initiative ancestor
        and uses that for ranking.

        Real-world example: PR #965 references AAP-60030, which rolls up to ANSTRAT-1780.
        The rank should come from ANSTRAT-1780 (Feature), not fail because AAP-60030 is not
        a Feature/Initiative.
        """
        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock a single PR referencing AAP-60030
        mock_fetch_pull_requests.return_value = [
            {
                "number": 965,
                "title": "Test PR with AAP reference",
                "user": {"login": "testuser"},
                "draft": False,
                "created_at": "2025-01-01T00:00:00Z",
                "html_url": "https://github.com/owner/repo/pull/965",
                "body": "| **Feature / Initiative** | [AAP-60030](https://issues.example.com/browse/AAP-60030) |",
            }
        ]

        mock_fetch_issue_events.return_value = [
            {"event": "ready_for_review", "created_at": "2025-01-02T00:00:00Z"}
        ]
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {
            "name": "Test User",
            "html_url": "https://github.com/testuser",
        }

        # Create mock JIRA client with hierarchy
        jira_client = Mock(spec=JiraClient)
        jira_client.base_url = "https://issues.example.com"

        # Mock metadata for both AAP-60030 (non-Feature) and ANSTRAT-1780 (Feature ancestor)
        jira_client.get_issues_metadata.return_value = {
            "AAP-60030": {
                "key": "AAP-60030",
                "fields": {
                    "summary": "AAP Story",
                    "issuetype": {"name": "Story"},  # Not Feature or Initiative
                    "status": {"name": "Backlog"},
                    "customfield_12345": None,  # No rank on AAP issue
                },
                "_rank_field_id": "customfield_12345",
            },
            "ANSTRAT-1780": {
                "key": "ANSTRAT-1780",
                "fields": {
                    "summary": "Feature ancestor",
                    "issuetype": {"name": "Feature"},
                    "status": {"name": "Backlog"},
                    "customfield_12345": "0|i00xyz:a",
                },
                "_rank_field_id": "customfield_12345",
            },
        }

        # Mock hierarchy traversal: AAP-60030 -> ANSTRAT-1780
        def mock_get_ancestors_side_effect(issue_key, metadata_cache=None, max_depth=5):  # noqa: ARG001
            if issue_key == "AAP-60030":
                return [
                    {
                        "key": "ANSTRAT-1780",
                        "fields": {
                            "issuetype": {"name": "Feature"},
                            "status": {"name": "Backlog"},
                            "customfield_12345": "0|i00xyz:a",
                        },
                        "_rank_field_id": "customfield_12345",
                    }
                ]
            return []

        jira_client.get_ancestors = Mock(side_effect=mock_get_ancestors_side_effect)

        # Mock the methods used by get_rank_for_pr
        def mock_get_issue_type(issue_data):
            return issue_data.get("fields", {}).get("issuetype", {}).get("name")

        def mock_get_issue_status(issue_data):
            return issue_data.get("fields", {}).get("status", {}).get("name")

        def mock_extract_rank_value(issue_data):
            return issue_data.get("fields", {}).get("customfield_12345")

        jira_client.get_issue_type.side_effect = mock_get_issue_type
        jira_client.get_issue_status.side_effect = mock_get_issue_status
        jira_client.extract_rank_value.side_effect = mock_extract_rank_value

        # Process PRs
        pull_requests, _ = fetch_and_process_pull_requests(
            "owner",
            "repo",
            jira_client=jira_client,
            jira_issue_patterns=[r"(AAP-\d+)", r"(ANSTRAT-\d+)"],
            github_token="test_token",
        )

        # Verify: should have one PR
        self.assertEqual(len(pull_requests), 1)

        # Verify: PR should have rank from ANSTRAT-1780 (the Feature ancestor)
        pr = pull_requests[0]
        self.assertIsNotNone(pr.get("rank"))
        self.assertIn("ANSTRAT-1780", pr["rank"])
        self.assertIn("0|i00xyz:a", pr["rank"].replace("_", "|"))

        # Verify: get_ancestors was called for AAP-60030
        jira_client.get_ancestors.assert_called()

    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_hierarchy_traversal_stops_at_first_feature(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_reviews,
        mock_fetch_user_details,
    ):
        """
        Test that hierarchy traversal stops at the first Feature/Initiative found,
        not traversing further up the chain.
        """
        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        # Mock PR referencing a Story
        mock_fetch_pull_requests.return_value = [
            {
                "number": 100,
                "title": "Test PR",
                "user": {"login": "testuser"},
                "draft": False,
                "created_at": "2025-01-01T00:00:00Z",
                "html_url": "https://github.com/owner/repo/pull/100",
                "body": "| **Feature / Initiative** | [STORY-100](https://issues.example.com/browse/STORY-100) |",
            }
        ]

        mock_fetch_issue_events.return_value = [
            {"event": "ready_for_review", "created_at": "2025-01-02T00:00:00Z"}
        ]
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {
            "name": "Test User",
            "html_url": "https://github.com/testuser",
        }

        jira_client = Mock(spec=JiraClient)
        jira_client.base_url = "https://issues.example.com"

        # Hierarchy: STORY-100 (Story) -> FEATURE-200 (Feature) -> INITIATIVE-300 (Initiative)
        jira_client.get_issues_metadata.return_value = {
            "STORY-100": {
                "key": "STORY-100",
                "fields": {
                    "summary": "Story",
                    "issuetype": {"name": "Story"},
                    "status": {"name": "Backlog"},
                    "customfield_12345": None,
                },
                "_rank_field_id": "customfield_12345",
            },
        }

        # Mock hierarchy: Story -> Feature -> Initiative
        # Should stop at Feature (first match)
        def mock_get_ancestors_side_effect(issue_key, metadata_cache=None, max_depth=5):  # noqa: ARG001
            if issue_key == "STORY-100":
                return [
                    {
                        "key": "FEATURE-200",
                        "fields": {
                            "issuetype": {"name": "Feature"},
                            "status": {"name": "Backlog"},
                            "customfield_12345": "0|i00aaa:a",
                        },
                        "_rank_field_id": "customfield_12345",
                    },
                    {
                        "key": "INITIATIVE-300",
                        "fields": {
                            "issuetype": {"name": "Initiative"},
                            "status": {"name": "Backlog"},
                            "customfield_12345": "0|i00bbb:b",
                        },
                        "_rank_field_id": "customfield_12345",
                    },
                ]
            return []

        jira_client.get_ancestors = Mock(side_effect=mock_get_ancestors_side_effect)

        def mock_get_issue_type(issue_data):
            return issue_data.get("fields", {}).get("issuetype", {}).get("name")

        def mock_get_issue_status(issue_data):
            return issue_data.get("fields", {}).get("status", {}).get("name")

        def mock_extract_rank_value(issue_data):
            return issue_data.get("fields", {}).get("customfield_12345")

        jira_client.get_issue_type.side_effect = mock_get_issue_type
        jira_client.get_issue_status.side_effect = mock_get_issue_status
        jira_client.extract_rank_value.side_effect = mock_extract_rank_value

        pull_requests, _ = fetch_and_process_pull_requests(
            "owner",
            "repo",
            jira_client=jira_client,
            jira_issue_patterns=[r"(STORY-\d+)", r"(FEATURE-\d+)", r"(INITIATIVE-\d+)"],
            github_token="test_token",
        )

        self.assertEqual(len(pull_requests), 1)
        pr = pull_requests[0]

        # Should use FEATURE-200 (first Feature/Initiative in hierarchy), not INITIATIVE-300
        self.assertIsNotNone(pr.get("rank"))
        self.assertIn("FEATURE-200", pr["rank"])
        self.assertIn("0|i00aaa:a", pr["rank"].replace("_", "|"))

    @patch("gh_pulls_summary.main.fetch_user_details")
    @patch("gh_pulls_summary.main.fetch_reviews")
    @patch("gh_pulls_summary.main.fetch_issue_events")
    @patch("gh_pulls_summary.main.fetch_pull_requests")
    def test_no_rank_when_no_feature_in_hierarchy(
        self,
        mock_fetch_pull_requests,
        mock_fetch_issue_events,
        mock_fetch_reviews,
        mock_fetch_user_details,
    ):
        """
        Test that no rank is assigned when there's no Feature/Initiative in the hierarchy.
        """
        from gh_pulls_summary.jira_client import JiraClient
        from gh_pulls_summary.main import fetch_and_process_pull_requests

        mock_fetch_pull_requests.return_value = [
            {
                "number": 100,
                "title": "Test PR",
                "user": {"login": "testuser"},
                "draft": False,
                "created_at": "2025-01-01T00:00:00Z",
                "html_url": "https://github.com/owner/repo/pull/100",
                "body": "| **Feature / Initiative** | [TASK-100](https://issues.example.com/browse/TASK-100) |",
            }
        ]

        mock_fetch_issue_events.return_value = [
            {"event": "ready_for_review", "created_at": "2025-01-02T00:00:00Z"}
        ]
        mock_fetch_reviews.return_value = []
        mock_fetch_user_details.return_value = {
            "name": "Test User",
            "html_url": "https://github.com/testuser",
        }

        jira_client = Mock(spec=JiraClient)
        jira_client.base_url = "https://issues.example.com"

        jira_client.get_issues_metadata.return_value = {
            "TASK-100": {
                "key": "TASK-100",
                "fields": {
                    "summary": "Task",
                    "issuetype": {"name": "Task"},
                    "status": {"name": "Backlog"},
                    "customfield_12345": None,
                },
                "_rank_field_id": "customfield_12345",
            },
        }

        # No ancestors (orphaned task)
        jira_client.get_ancestors = Mock(return_value=[])

        def mock_get_issue_type(issue_data):
            return issue_data.get("fields", {}).get("issuetype", {}).get("name")

        def mock_get_issue_status(issue_data):
            return issue_data.get("fields", {}).get("status", {}).get("name")

        def mock_extract_rank_value(issue_data):
            return issue_data.get("fields", {}).get("customfield_12345")

        jira_client.get_issue_type.side_effect = mock_get_issue_type
        jira_client.get_issue_status.side_effect = mock_get_issue_status
        jira_client.extract_rank_value.side_effect = mock_extract_rank_value

        pull_requests, _ = fetch_and_process_pull_requests(
            "owner",
            "repo",
            jira_client=jira_client,
            jira_issue_patterns=[r"(TASK-\d+)"],
            github_token="test_token",
        )

        self.assertEqual(len(pull_requests), 1)
        pr = pull_requests[0]

        # Should have no rank (no Feature/Initiative in hierarchy)
        # Empty string is used instead of None for easier markdown formatting
        self.assertEqual(pr.get("rank"), "")


class TestMarkdownRowFormattingForSyntheticEntries(unittest.TestCase):
    """Test cases for markdown table row formatting of synthetic JIRA entries."""

    def test_create_markdown_table_row_for_synthetic_entry(self):
        """Test that synthetic JIRA entries are formatted correctly in markdown."""
        from gh_pulls_summary.main import create_markdown_table_row

        # Synthetic JIRA entry (no PR number, has jira_key reference)
        synthetic_pr = {
            "date": "",
            "title": None,
            "number": None,
            "url": None,
            "jira_key": "ANSTRAT-1234",
            "author_name": "",
            "author_url": "",
            "reviews": 0,
            "approvals": 0,
            "changes": "",
            "pr_body_urls_dict": {},
            "rank": "0_i00001 ANSTRAT-1234",
        }

        # JIRA issues dict
        jira_issues = {
            "ANSTRAT-1234": {
                "title": "Implement feature XYZ",
                "url": "https://issues.example.com/browse/ANSTRAT-1234",
                "rank": "0_i00001 ANSTRAT-1234",
            }
        }

        row = create_markdown_table_row(
            synthetic_pr, url_column=False, rank_column=True, jira_issues=jira_issues
        )

        # Should have JIRA title linked to JIRA URL (no PR number)
        self.assertIn(
            "[Implement feature XYZ](https://issues.example.com/browse/ANSTRAT-1234)",
            row,
        )
        # Should not have PR number format #[123]
        self.assertNotIn("#[", row)
        # Should have empty fields for author, changes, approvals
        self.assertIn("|  |  |  |", row)  # Empty date, author, changes, approvals
        # Should have rank
        self.assertIn("0_i00001 ANSTRAT-1234", row)

    def test_create_markdown_table_row_for_normal_pr(self):
        """Test that normal PR entries are formatted correctly in markdown."""
        from gh_pulls_summary.main import create_markdown_table_row

        # Normal PR entry
        normal_pr = {
            "date": "2025-01-08",
            "title": "Add feature",
            "number": 123,
            "url": "https://github.com/owner/repo/pull/123",
            "author_name": "John Doe",
            "author_url": "https://github.com/johndoe",
            "reviews": 2,
            "approvals": 2,
            "changes": 0,
            "pr_body_urls_dict": {},
            "rank": "0_i00002 ANSTRAT-5678",
        }

        row = create_markdown_table_row(
            normal_pr, url_column=False, rank_column=True, jira_issues=None
        )

        # Should have PR number format
        self.assertIn("Add feature #[123](https://github.com/owner/repo/pull/123)", row)
        # Should have author
        self.assertIn("[John Doe](https://github.com/johndoe)", row)
        # Should have date
        self.assertIn("2025-01-08", row)
        # Should have reviews formatted
        self.assertIn("2 of 2", row)
        # Should have rank
        self.assertIn("0_i00002 ANSTRAT-5678", row)


class TestJiraClientAncestorMethods(unittest.TestCase):
    """Test cases for JIRA client ancestor traversal methods."""

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_discover_parent_fields_success(self, mock_get):
        """Test successful discovery of parent fields."""
        from gh_pulls_summary.jira_client import JiraClient

        # Mock editmeta response with parent fields
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "fields": {
                "customfield_10014": {
                    "name": "Parent Link",
                    "schema": {"custom": "com.atlassian.jpo:jpo-custom-field-parent"},
                },
                "customfield_10015": {
                    "name": "Epic Link",
                    "schema": {"custom": "com.pyxis.greenhopper.jira:gh-epic-link"},
                },
                "summary": {"name": "Summary", "schema": {"type": "string"}},
            }
        }
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        parent_fields = client._discover_parent_fields("TEST-123", "TEST", "Story")

        # Should discover both parent-type fields
        self.assertEqual(len(parent_fields), 2)
        self.assertIn("customfield_10014", parent_fields)
        self.assertIn("customfield_10015", parent_fields)

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_discover_parent_fields_caching(self, mock_get):
        """Test that parent field discovery results are cached."""
        from gh_pulls_summary.jira_client import JiraClient

        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "fields": {
                "customfield_10014": {
                    "name": "Parent Link",
                    "schema": {"custom": "com.atlassian.jpo:jpo-custom-field-parent"},
                }
            }
        }
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        # First call should hit API
        parent_fields1 = client._discover_parent_fields("TEST-123", "TEST", "Story")
        self.assertEqual(mock_get.call_count, 1)

        # Second call with same project:type should use cache
        parent_fields2 = client._discover_parent_fields("TEST-124", "TEST", "Story")
        self.assertEqual(mock_get.call_count, 1)  # No additional API call

        # Results should be the same
        self.assertEqual(parent_fields1, parent_fields2)

    def test_find_parent_key_from_subtask_parent(self):
        """Test finding parent key from standard subtask parent field."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {
            "key": "TEST-123",
            "fields": {
                "parent": {"key": "TEST-100"},
                "project": {"key": "TEST"},
                "issuetype": {"name": "Subtask"},
            },
        }

        parent_key = client._find_parent_key(issue_data)
        self.assertEqual(parent_key, "TEST-100")

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_find_parent_key_from_custom_field(self, mock_get):
        """Test finding parent key from custom parent link field."""
        from gh_pulls_summary.jira_client import JiraClient

        # Mock editmeta response
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "fields": {
                "customfield_10014": {
                    "name": "Parent Link",
                    "schema": {"custom": "com.atlassian.jpo:jpo-custom-field-parent"},
                }
            }
        }
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        issue_data = {
            "key": "TEST-123",
            "fields": {
                "project": {"key": "TEST"},
                "issuetype": {"name": "Story"},
                "customfield_10014": "TEST-100",  # Parent link
            },
        }

        parent_key = client._find_parent_key(issue_data)
        self.assertEqual(parent_key, "TEST-100")

    def test_find_parent_key_no_parent(self):
        """Test finding parent when no parent exists."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")

        issue_data = {
            "key": "TEST-123",
            "fields": {
                "project": {"key": "TEST"},
                "issuetype": {"name": "Story"},
            },
        }

        parent_key = client._find_parent_key(issue_data)
        self.assertIsNone(parent_key)

    def test_get_ancestors_with_metadata_cache(self):
        """Test get_ancestors using metadata cache (no API calls)."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        # Build metadata cache: TASK-100 -> STORY-50 -> FEATURE-10
        metadata_cache = {
            "TASK-100": {
                "key": "TASK-100",
                "fields": {
                    "parent": {"key": "STORY-50"},
                    "issuetype": {"name": "Task"},
                },
            },
            "STORY-50": {
                "key": "STORY-50",
                "fields": {
                    "parent": {"key": "FEATURE-10"},
                    "issuetype": {"name": "Story"},
                },
            },
            "FEATURE-10": {
                "key": "FEATURE-10",
                "fields": {"issuetype": {"name": "Feature"}},
            },
        }

        ancestors = client.get_ancestors("TASK-100", metadata_cache=metadata_cache)

        self.assertEqual(len(ancestors), 2)
        self.assertEqual(ancestors[0]["key"], "STORY-50")
        self.assertEqual(ancestors[1]["key"], "FEATURE-10")

    def test_get_ancestors_caching(self):
        """Test that get_ancestors caches results."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        metadata_cache = {
            "TASK-100": {
                "key": "TASK-100",
                "fields": {
                    "parent": {"key": "STORY-50"},
                    "issuetype": {"name": "Task"},
                },
            },
            "STORY-50": {
                "key": "STORY-50",
                "fields": {"issuetype": {"name": "Story"}},
            },
        }

        # First call
        ancestors1 = client.get_ancestors("TASK-100", metadata_cache=metadata_cache)

        # Second call should use internal cache
        ancestors2 = client.get_ancestors("TASK-100")

        self.assertEqual(ancestors1, ancestors2)
        self.assertEqual(len(ancestors2), 1)

    def test_get_ancestors_empty_cache(self):
        """Test that get_ancestors caches empty results."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        metadata_cache = {
            "TASK-100": {
                "key": "TASK-100",
                "fields": {"issuetype": {"name": "Task"}},  # No parent
            }
        }

        # First call - no ancestors found
        ancestors1 = client.get_ancestors("TASK-100", metadata_cache=metadata_cache)

        # Second call should return cached empty result
        ancestors2 = client.get_ancestors("TASK-100")

        self.assertEqual(ancestors1, [])
        self.assertEqual(ancestors2, [])

    def test_get_ancestors_cycle_detection(self):
        """Test that get_ancestors detects and handles cycles without infinite loop."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        # Create a cycle: A -> B -> C -> B (C points back to B)
        metadata_cache = {
            "TASK-A": {
                "key": "TASK-A",
                "fields": {
                    "parent": {"key": "TASK-B"},
                    "issuetype": {"name": "Task"},
                },
            },
            "TASK-B": {
                "key": "TASK-B",
                "fields": {
                    "parent": {"key": "TASK-C"},
                    "issuetype": {"name": "Task"},
                },
            },
            "TASK-C": {
                "key": "TASK-C",
                "fields": {
                    "parent": {"key": "TASK-B"},  # Cycle!
                    "issuetype": {"name": "Task"},
                },
            },
        }

        ancestors = client.get_ancestors("TASK-A", metadata_cache=metadata_cache)

        # Should stop at cycle detection and not infinite loop
        # Actual path: A -> B -> C -> B (detected), so 3 ancestors
        self.assertEqual(len(ancestors), 3)
        self.assertEqual(ancestors[0]["key"], "TASK-B")
        self.assertEqual(ancestors[1]["key"], "TASK-C")
        self.assertEqual(ancestors[2]["key"], "TASK-B")

    def test_get_ancestors_max_depth(self):
        """Test that get_ancestors respects max_depth."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        # Build long chain: TASK-5 -> TASK-4 -> TASK-3 -> TASK-2 -> TASK-1
        metadata_cache = {}
        for i in range(1, 6):
            parent_key = f"TASK-{i - 1}" if i > 1 else None
            metadata_cache[f"TASK-{i}"] = {
                "key": f"TASK-{i}",
                "fields": {
                    "parent": {"key": parent_key} if parent_key else {},
                    "issuetype": {"name": "Task"},
                },
            }

        ancestors = client.get_ancestors(
            "TASK-5", metadata_cache=metadata_cache, max_depth=2
        )

        # Should stop at max_depth=2
        self.assertEqual(len(ancestors), 2)
        self.assertEqual(ancestors[0]["key"], "TASK-4")
        self.assertEqual(ancestors[1]["key"], "TASK-3")

    def test_get_ancestors_missing_from_cache(self):
        """Test get_ancestors when parent is missing from cache (old behavior for reference)."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        metadata_cache = {
            "TASK-100": {
                "key": "TASK-100",
                "fields": {
                    "parent": {"key": "STORY-50"},  # Parent not in cache
                    "issuetype": {"name": "Task"},
                },
            }
        }

        ancestors = client.get_ancestors("TASK-100", metadata_cache=metadata_cache)

        # Should stop when parent not found in cache and API call fails
        self.assertEqual(len(ancestors), 0)

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    def test_get_ancestors_api_fallback_when_parent_missing(self, mock_get):
        """Test that get_ancestors falls back to API when parent is missing from cache."""
        from gh_pulls_summary.jira_client import JiraClient

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12345"

        # Cache has the child, but not the parent or grandparent
        metadata_cache = {
            "STORY-100": {
                "key": "STORY-100",
                "fields": {
                    "customfield_12311140": "EPIC-50",  # Epic Link to parent
                    "issuetype": {"name": "Story"},
                    "project": {"key": "TEST"},
                },
            }
        }

        # Mock API responses for missing parent and grandparent
        def mock_api_response(*args, **_kwargs):
            url = args[0]
            response = Mock()
            response.status_code = 200

            if "STORY-100/editmeta" in url:
                # editmeta for Story to discover parent fields
                response.json.return_value = {
                    "fields": {
                        "customfield_12311140": {
                            "name": "Epic Link",
                            "schema": {
                                "custom": "com.pyxis.greenhopper.jira:gh-epic-link"
                            },
                        }
                    }
                }
            elif "EPIC-50/editmeta" in url:
                # editmeta for Epic to discover parent fields
                response.json.return_value = {
                    "fields": {
                        "customfield_12313140": {
                            "name": "Parent Link",
                            "schema": {
                                "custom": "com.atlassian.jpo:jpo-custom-field-parent"
                            },
                        }
                    }
                }
            elif "EPIC-50" in url:
                # EPIC-50 parent data
                response.json.return_value = {
                    "key": "EPIC-50",
                    "fields": {
                        "customfield_12313140": "FEATURE-10",  # Parent Link to grandparent
                        "issuetype": {"name": "Epic"},
                        "project": {"key": "TEST"},
                        "summary": "Epic 50",
                        "status": {"name": "In Progress"},
                        "priority": {"name": "High"},
                    },
                }
            elif "FEATURE-10/editmeta" in url:
                # editmeta for Feature
                response.json.return_value = {"fields": {}}
            elif "FEATURE-10" in url:
                # FEATURE-10 grandparent data
                response.json.return_value = {
                    "key": "FEATURE-10",
                    "fields": {
                        "issuetype": {"name": "Feature"},
                        "project": {"key": "TEST"},
                        "summary": "Feature 10",
                        "status": {"name": "In Progress"},
                        "priority": {"name": "High"},
                        "customfield_12345": "0|i00001:",  # Rank field
                    },
                }
            return response

        mock_get.side_effect = mock_api_response

        ancestors = client.get_ancestors("STORY-100", metadata_cache=metadata_cache)

        # Should have fetched both parents via API
        self.assertEqual(len(ancestors), 2)
        self.assertEqual(ancestors[0]["key"], "EPIC-50")
        self.assertEqual(ancestors[1]["key"], "FEATURE-10")


class TestJiraRateLimitRetry(unittest.TestCase):
    """Test JIRA rate limit retry logic."""

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    @patch("time.sleep")
    def test_rate_limit_retry_success(self, mock_sleep, mock_get):
        """Test successful retry after rate limit error."""
        # First call returns 429, second call returns 200
        mock_response_429 = Mock()
        mock_response_429.status_code = 429
        mock_response_429.text = '{"message":"Rate limit exceeded."}'

        mock_response_200 = Mock()
        mock_response_200.status_code = 200
        mock_response_200.json.return_value = {
            "key": "TEST-123",
            "fields": {
                "summary": "Test issue",
                "issuetype": {"name": "Feature"},
            },
        }

        mock_get.side_effect = [mock_response_429, mock_response_200]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12311940"

        issue_data = client.get_issue("TEST-123")

        # Should have succeeded on second try
        self.assertEqual(issue_data["key"], "TEST-123")

        # Should have slept once with 2 seconds delay
        mock_sleep.assert_called_once_with(2)

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    @patch("time.sleep")
    def test_rate_limit_retry_exhausted(self, mock_sleep, mock_get):
        """Test that retry gives up after max_retries."""
        # All calls return 429
        mock_response = Mock()
        mock_response.status_code = 429
        mock_response.text = '{"message":"Rate limit exceeded."}'
        mock_get.return_value = mock_response

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12311940"

        with self.assertRaises(JiraClientError) as context:
            client.get_issue("TEST-123")

        self.assertIn("Rate limit exceeded", str(context.exception))
        self.assertIn("after 3 retries", str(context.exception))

        # Should have slept 3 times with exponential backoff: 2, 4, 8
        self.assertEqual(mock_sleep.call_count, 3)
        mock_sleep.assert_any_call(2)
        mock_sleep.assert_any_call(4)
        mock_sleep.assert_any_call(8)

    @patch("gh_pulls_summary.jira_client.requests.Session.get")
    @patch("time.sleep")
    def test_rate_limit_retry_exponential_backoff(self, mock_sleep, mock_get):
        """Test exponential backoff timing."""
        # First two calls return 429, third returns 200
        mock_response_429 = Mock()
        mock_response_429.status_code = 429
        mock_response_429.text = '{"message":"Rate limit exceeded."}'

        mock_response_200 = Mock()
        mock_response_200.status_code = 200
        mock_response_200.json.return_value = {
            "key": "TEST-123",
            "fields": {"summary": "Test", "issuetype": {"name": "Feature"}},
        }

        mock_get.side_effect = [
            mock_response_429,
            mock_response_429,
            mock_response_200,
        ]

        client = JiraClient(base_url="https://issues.example.com", token="testtoken")
        client._rank_field_id = "customfield_12311940"

        issue_data = client.get_issue("TEST-123")

        # Should have succeeded on third try
        self.assertEqual(issue_data["key"], "TEST-123")

        # Should have slept twice with exponential backoff: 2, 4 seconds
        self.assertEqual(mock_sleep.call_count, 2)
        calls = [call[0][0] for call in mock_sleep.call_args_list]
        self.assertEqual(calls, [2, 4])


if __name__ == "__main__":
    unittest.main()
