name: Update Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  update-coverage-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run tests and generate coverage
      run: make coverage
    
    - name: Extract coverage percentage
      run: |
        COVERAGE=$(coverage report | tail -1 | awk '{print $4}' | sed 's/%//')
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        echo "Coverage: $COVERAGE%"
    
    - name: Create coverage badge
      run: |
        mkdir -p .github/badges
        echo '{"schemaVersion": 1, "label": "coverage", "message": "'$COVERAGE'%", "color": "brightgreen"}' > .github/badges/coverage.json
    
    - name: Commit coverage badge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/badges/coverage.json
        if ! git diff --staged --quiet; then
          git commit -m "Update coverage badge [skip ci]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        else
          echo "No changes to coverage badge"
        fi 